- name: 'Test'
  hosts: localhost
  connection: local
  tasks:
    - name: line replace
      lineinfile:
        path: ./file2
        line: "####"
        regexp: "^line2 test2$"
        state: present
        create: True
